version: '2'
# Shared Data Volume
volumes:
  telegraf-conf:
  influxdb-conf:
  chronograf-conf:
  kapacitor-conf:
  influxdb-data:
  chronograf-data:
  kapacitor-data:
services:
  # Data Volume Configured Container
  tick-data:
    image: nmrmsys/tick-data:v0.1.4
    tty: true
    network_mode: none
    volumes:
        - telegraf-conf:/etc/telegraf
        - influxdb-conf:/etc/influxdb
        - chronograf-conf:/usr/share/chronograf
        - kapacitor-conf:/etc/kapacitor
        - influxdb-data:/var/lib/influxdb
        - chronograf-data:/var/lib/chronograf
        - kapacitor-data:/var/lib/kapacitor
    labels:
      io.rancher.container.hostname_override: container_name
  # Define a Telegraf service
  telegraf:
    image: telegraf:1.7.0
    volumes:
        - telegraf-conf:/etc/telegraf
    ports:
      - "6514:6514"
    #  - "8092:8092/udp"
    #  - "8094:8094"
    #  - "8125:8125/udp"
    labels:
      io.rancher.container.hostname_override: container_name
    links:
      - influxdb
  # Define an InfluxDB service
  influxdb:
    image: nmrmsys/influxdb-nightly # influxdb:1.5.3
    volumes:
        - influxdb-conf:/etc/influxdb
        - influxdb-data:/var/lib/influxdb
    ports:
      - "8082:8082"
      - "8086:8086"
    environment:
      INFLUXDB_ADMIN_ENABLED: 'true'
    labels:
      io.rancher.container.hostname_override: container_name
    links:
      - tick-data
  # Define a Chronograf service
  chronograf:
    image: nmrmsys/chronograf-nightly # chronograf:1.5.0
    volumes:
        - chronograf-conf:/usr/share/chronograf
        - chronograf-data:/var/lib/chronograf
    environment:
      INFLUXDB_URL: http://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
      CANNED_PATH: /usr/share/chronograf/canned
      FLAX_URL: http://fluxd:8093
    ports:
      - "8888:8888"
    labels:
      io.rancher.container.hostname_override: container_name
    links:
      - influxdb
      - kapacitor
      - fluxd
  # Define a Kapacitor service
  kapacitor:
    image: kapacitor:1.5.0
    volumes:
        - kapacitor-conf:/etc/kapacitor
        - kapacitor-data:/var/lib/kapacitor
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    ports:
      - "9092:9092"
    labels:
      io.rancher.container.hostname_override: container_name
    links:
      - influxdb
  # Define a fluxd service
  fluxd:
    image: nmrmsys/flux-nightly
    environment:
      - "FLUXD_STORAGE_HOSTS=influxdb:8082"
    ports:
      - "8093:8093"
    labels:
      io.rancher.container.hostname_override: container_name
    links:
      - influxdb
  # Define a service for using the influx CLI tool.
  # docker-compose run influxdb-cli
#  influxdb-cli:
#    image: influxdb:1.4.3
#    entrypoint:
#      - influx
#      - -host
#      - influxdb
#    links:
#      - influxdb
  # Define a service for using the kapacitor CLI tool.
  # docker-compose run kapacitor-cli
#  kapacitor-cli:
#    image: kapacitor:1.4.0
#    entrypoint: bash
#    environment:
#      KAPACITOR_URL: http://kapacitor:9092
#    links:
#      - kapacitor
